#!/bin/bash
if [ -z "$1" ]; then
  git commit --amend
else
  echo "==========================="
  echo ""
  echo "ATTENTION! Alter \"pick\" to \"reword\" in the commit you want to edit."
  echo "After that, save and close the file, so you will be able to edit the commit message."
  echo ""
  echo "To publish you must run \"git put --force\"."
  echo "This is NOT RECOMMENDED if commits have already been made to a remote repository and other collaborators are active."
  echo ""
  echo "==========================="
  git rebase -i $1
fi
