#!/bin/bash
if [[ "$@" == *"-y"* || "$@" == *"--yes"* ]]; then
  for param; do
    [[ ! $param == '-y' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams

  for param; do
    [[ ! $param == '--yes' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams

  if [ $# -eq 0 ]; then
    git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
  else
    git reset --hard origin/$1
  fi
else
  echo "Are you sure you want to wipe (hard reset) \"$(git rev-parse --abbrev-ref HEAD)\" branch? (y/N)"
  read REPLY
  if [[ "$REPLY" =~ ^[Yy]$ ]]; then
    if [ $# -eq 0 ]; then
      git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
    else
      git reset --hard origin/$1
    fi
  fi
fi
