#!/bin/bash
if [ -z "$1" ]; then
  git branch -a | grep -v ‘remotes’
elif [ "$1" == "-r" ]; then
  git branch -r | grep -v ‘remotes’
elif [ "$1" == "-l" ]; then
  git branch -l | grep -v ‘remotes’
else
  git branch -a | grep -v ‘remotes’
fi
