#!/bin/bash
for ((i = 1; i <= $#; i++)); do
  if [[ "${!i}" == "-a" || "${!i}" == "--author" ]]; then
    ARG=$(($i + 1))
    AUTHOR=${!ARG}
    shift
  elif [[ "${!i}" == "-s" || "${!i}" == "--since" ]]; then
    ARG=$(($i + 1))
    SINCE=${!ARG}
    shift
  elif [[ "${!i}" == "-u" || "${!i}" == "--until" ]]; then
    ARG=$(($i + 1))
    UNTIL=${!ARG}
    shift
  elif [[ "${!i}" == "-e" || "${!i}" == "--exclude" ]]; then
    EXCLUDE=true
  else
    SEARCH_TERMS=${!i// /'\s'}
  fi
done

if [[ -n "$SEARCH_TERMS" ]]; then
  QUERY+="--grep $SEARCH_TERMS "
fi
if [[ -n "$AUTHOR" ]]; then
  QUERY+="--author $AUTHOR "
fi
if [[ -n "$SINCE" ]]; then
  QUERY+="--since $SINCE "
fi
if [[ -n "$UNTIL" ]]; then
  QUERY+="--until $UNTIL "
fi
if [[ -n "$EXCLUDE" ]]; then
  QUERY+="--invert-grep "
fi

git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %C(green)(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit $QUERY
