#!/bin/bash
if [ "$1" == "-o" -o "$1" == "--origin" ]; then
  shift
  BRANCH_NAME=${@}
  BRANCH_NAME=${BRANCH_NAME// /-}
  git checkout -b release/${BRANCH_NAME}
  git push -u origin release/${BRANCH_NAME}
else
  BRANCH_NAME=${@}
  BRANCH_NAME=${BRANCH_NAME// /-}
  git checkout -b release/${BRANCH_NAME}
fi
