#!/bin/bash
if [ "$1" == "-o" -o "$1" == "--origin" ]; then
  shift
  BRANCH_NAME=${@}
  BRANCH_NAME=${BRANCH_NAME// /-}
  git checkout -b hotfix/${BRANCH_NAME}
  git push -u origin hotfix/${BRANCH_NAME}
else
  BRANCH_NAME=${@}
  BRANCH_NAME=${BRANCH_NAME// /-}
  git checkout -b hotfix/${BRANCH_NAME}
fi
