#!/bin/bash
HAS_TO_ADD=false
HAS_TO_PUT=false

if [[ "$@" == *"-a"* ]]; then
  HAS_TO_ADD=true
  for param; do
    [[ ! $param == '-a' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams
fi

if [[ "$@" == *"-p"* ]]; then
  HAS_TO_PUT=true
  for param; do
    [[ ! $param == '-p' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams
fi

if [[ "$@" == *"-ap"* ]]; then
  HAS_TO_PUT=true
  HAS_TO_ADD=true
  for param; do
    [[ ! $param == '-ap' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams
fi

if [[ "$@" == *"-pa"* ]]; then
  HAS_TO_PUT=true
  HAS_TO_ADD=true
  for param; do
    [[ ! $param == '-pa' ]] && newparams+=("$param")
  done
  set -- "${newparams[@]}"
  unset newparams
fi

if [ -z "$1" ]; then
  if [ $HAS_TO_ADD = true ]; then
    git add .
    git commit -am "perf: " -e
  else
    git commit -m "perf: " -e
  fi
elif [ "$1" == "-s" ]; then
  if [ $HAS_TO_ADD = true ]; then
    git add .
    git commit -am "perf(${2}): ${@:3}"
  else
    git commit -m "perf(${2}): ${@:3}"
  fi
else
  if [ $HAS_TO_ADD = true ]; then
    git add .
    git commit -am "perf: ${@}"
  else
    git commit -m "perf: ${@}"
  fi
fi

if [ $HAS_TO_PUT = true ]; then
  git push origin $(git rev-parse --abbrev-ref HEAD)
fi
