#!/bin/bash
if [ -z "$1" ]; then
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "perf: " -e
  else
    git commit -m "perf: " -e
  fi
elif [ "$1" == "-s" ]; then
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "perf(${2}): ${@:3}"
  else
    git commit -m "perf(${2}): ${@:3}"
  fi
else
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "perf: ${@}"
  else
    git commit -m "perf: ${@}"
  fi
fi
