#!/bin/bash
if [ -z "$1" ] || [[ "$@" == *"-a"* && -z "$2" ]]; then
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "fix: " -e
  else
    git commit -m "fix: " -e
  fi
elif [ "$1" == "-s" ]; then
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "fix(${2}): ${@:3}"
  else
    git commit -m "fix(${2}): ${@:3}"
  fi
else
  if [[ "$@" == *"-a"* ]]; then
    git add .
    for param; do
      [[ ! $param == '-a' ]] && newparams+=("$param")
    done
    set -- "${newparams[@]}"
    unset newparams
    git commit -am "fix: ${@}"
  else
    git commit -m "fix: ${@}"
  fi
fi
